name: First workflow
# there are many events which we can trigeer, but currenlt we have used the workflow_dispatch
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello World"
      - name: End greeting
        run: echo "Done-bye World"      
